### ISSUE TITLE
"Open with Haxe Studio" shell integration

### ISSUE THREAD

**Issue by ianharrigan** [haxe4e/haxe-studio#3]
Importing projects into the default workspace is "fine"... however, for people like myself who tend to work on loads and loads and loads of throw away test apps it could get a little old.

Im wondering how feasible it would be to right click a folder and have a "Open with Haxe4e" appear on in, much like VSCode does, this will make importing projects sooooo much simpler. 

![image](https://user-images.githubusercontent.com/3024242/135218118-ba82620d-097f-4ae3-bf38-b68e80292e97.png)

**Comment by sebthom** [comment]
There is this plugin https://eclipsehowl.wordpress.com/2010/05/06/open-with-eclipse/  but I don't think it will import a project but only opens the selected file in an Eclipse Editor.

**Comment by sebthom** [comment]
![image](https://user-images.githubusercontent.com/426959/139584347-3ccaa594-c339-47b0-aa67-ee9201ed5a96.png)
