### ISSUE TITLE
Debug Clients?

### ISSUE THREAD

**Issue by hoseyjoe** [haxe4e/haxe-studio#42]
What is the workflow in Haxe Studio?  Can you debug a Heaps Application, cpp app, or is it best to do JS front end?

**Comment by sebthom** [comment]
I haven't fully wrapped my head around how to implement consistent debugging, the large number of Haxe targets (each with their own quirks) and all the different build systems doesn't make things easier.

The whole debugging experience is still work in progress. So far I implemented debugger support for the **interp/eval** target, e.g. if you have a hxml with the `--interp` flag you can right-click on it and select `Debug As > Haxe Program`. Then step debugging, variable inspection etc. works as usually done in Eclipse.

For debugging back-end apps targeting nodejs, one can generate the JS file and select `Debug As > Node Program`. However this requires to set the breakpoints in the JS code.
