### ISSUE TITLE
Run Configuration not working 

### ISSUE THREAD

**Issue by ianharrigan** [haxe4e/haxe-studio#7]
So the first issue is that when creating a run config to launch an application:

![image](https://user-images.githubusercontent.com/3024242/137454415-7e414814-28df-4232-b02d-3a30f06ec2e1.png)

You get this:

![image](https://user-images.githubusercontent.com/3024242/137454447-db07195d-39d9-4d27-8ce3-aed4fe1e0330.png)

Presumably because (for some reason) eclipse is trying to run using WSL. The second is that in the "shell script" box you have to use an absolute path for the .bat which could become a pain if you are constantly switching between 10s / 100s of projects

**Comment by sebthom** [comment]
Can we close this?

**Comment by ianharrigan** [comment]
Yup, this is also fixed - and after using the right click on the .bat the run is nicely setup for me, so i can reuse it via the "play" button

![image](https://user-images.githubusercontent.com/3024242/143293596-5adf9f9b-5b90-49fa-8ca8-aee976499980.png)
