### ISSUE TITLE
Node not found?

### ISSUE THREAD

**Issue by hoseyjoe** [haxe4e/haxe-studio#9]
Windows.  Node runs on cmd line.  Tested project with Ian and code completion worked for him.  It doesn't for me

![image](https://user-images.githubusercontent.com/2074385/145148725-8401ae7f-339f-45a1-bf55-9730ed317abd.png)

![image](https://user-images.githubusercontent.com/2074385/145150284-db7edcd5-ae8a-4c92-a70f-8dd34e065193.png)

![image](https://user-images.githubusercontent.com/2074385/145150313-48778b72-f0e1-43b6-85b5-8359d214aa25.png)

**Comment by sebthom** [comment]
Node is bundled with HS so it should not matter whether it is installed or not. 
How did you install HS, using the portable installer exe or the zip file?
Also can you check the `workspace\.metadata\.log` if there are any exceptions with stacktrace that might relate to this issue?

**Comment by hoseyjoe** [comment]
I started with instaler but I am currently runnning from the zip.

[log.log](https://github.com/haxe4e/haxe-studio/files/7677486/log.log)

I can run the node, from cmd, found here  
C:\IDEs\HaxeStudio\workspace\.metadata\.plugins\org.eclipse.wildwebdeveloper.embedder.node\node-v16.9.0-win-x64

**Comment by sebthom** [comment]
Are you targeting nodejs? Because this exception basically means that the Haxe Language Server itself or a macro executed by the Haxe compiler cannot find node.
The node bundled with HS is only used for the (not yet working) debugger support.
```python
org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Error: 'node' is not recognized as an internal or external command,
operable program or batch file.
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:209)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
	at org.eclipse.lsp4e.LanguageServerWrapper.lambda$4(LanguageServerWrapper.java:260)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```
Can you try to create a helloworld haxe project targeting eval to see if code completion works at least there.

**Comment by hoseyjoe** [comment]
Unzipped and started fresh with different workspace. Log is cleaner but same issue.  
[log.log](https://github.com/haxe4e/haxe-studio/files/7677656/log.log)

With new project I get code completion! So I tried importing old project.

1. File->import Haxe->haxeProject
2. I choose the project outside of workspace (on desktop) and I have issue

I moved project to workspace and tried importing it...same issue.

For reference this is the project 
[Table.zip](https://github.com/haxe4e/haxe-studio/files/7677740/Table.zip)

**Comment by ianharrigan** [comment]
As far as im aware the project isnt targeting node, its targeting haxeui-html (which is js output). 

> Because this exception basically means that the Haxe Language Server itself or a macro executed by the Haxe compiler cannot find node

> The node bundled with HS is only used for the (not yet working) debugger support.

So the bundled node is used for debugging and node on the users system is used for completion? Any thoughts as to why eclipse cant seem to find the system node if that is the case... does it need to be a specific version? 

Interestingly, if i take the exact same project, i get completion

**Comment by hoseyjoe** [comment]
Some logging on HaxeLangServerLauncher.java#L50-L55 would help determine the issue is my guess.  

It's weird that a new project works but imported project has issue

**Comment by ianharrigan** [comment]
> start another node process or haxe or a macro
certainly no haxeui macro is starting off a node process

I wonder if lang server could be? Like some type of threading or something weird? @hoseyjoe what version of haxe are you using? (not sure it would make a difference but it seems weird that its totally fine for me)

**Comment by sebthom** [comment]
@hoseyjoe is it possible for you provide us a zipped workspace containing a project that fails?

**Comment by ianharrigan** [comment]
> is it possible for you to provide us a zipped workspace containing a project that fails?

The project is attached here (workspace isnt though)

**Comment by hoseyjoe** [comment]
workspace is too large with .metadata to upload to github
These are 2 projects in workspace.  Is there something in metadata I can upload for you?  
[workspace.zip](https://github.com/haxe4e/haxe-studio/files/7678196/workspace.zip)

**Comment by hoseyjoe** [comment]
This is everything except plugins folder in metadata
[files.metadata.zip](https://github.com/haxe4e/haxe-studio/files/7678208/files.metadata.zip)

**Comment by hoseyjoe** [comment]
for reference haxe
Haxe Compiler 4.2.4 - (C)2005-2020 Haxe Foundation

**Comment by hoseyjoe** [comment]
This is actuall a 7z file not a zip.  but it is small enough to upload now

[workspace.zip](https://github.com/haxe4e/haxe-studio/files/7678778/workspace.zip)

**Comment by hoseyjoe** [comment]
well maybe this helps?  Maybe not.  I made another hello world.  Adding libs to hxml seems problematic with completion?

I had code completion with
-cp src
-main Main
--interp

After I didnt have code completion
-lib haxeui-heaps
-lib haxeui-core
-cp src
-main Main
--interp

Both libs are "git" installed in haxelib. I did not change any code. Just the build.hxml.  Code completion stops immediately upon savign hxml and restarting HS causes onHaxeCacheBuildFailed: null

I tested non git installed libs and they had issue.

I have haxelib installed with haxe at c:/sdks/haxe not normal installation path?

LSS: Adding libs to build.hxml causes code completion to break for me

**Comment by sebthom** [comment]
One thing comes to my mind. I don't know how you unzipped HaxeStudio. I have seen unpackers that have issues on Windows extracting Eclipse bundles because of the long nested paths and then cannot extract/write some of the files. Maybe you can try to use the HaxeStudioPortable.paf.exe (self-extracting 7z archive) or unzip the *.zip file using the 64bit version of the 7Zip Manager.

**Comment by hoseyjoe** [comment]
So when I add libs and restart the error occurs (code completion stops when hxml is saved).  When I remove the lib and restart the error doesn't happen.  Totally bizarre.

I tried paf to c:\HaxeStudio_PAF
![image](https://user-images.githubusercontent.com/2074385/145478547-1ac29cde-812f-44ed-9562-a2e85fd46eb6.png)

**Comment by hoseyjoe** [comment]
I have English language based windows?  Do you use German?  IDK maybe the variables being passed to haxe are corrupted somehow like Im not utf8 compatible and it is passing in a bom or something

**Comment by sebthom** [comment]
I am using English, and Ian too, we both can't reproduce it. So I doubt it is a language/locale issue. 

Can you check if outline/code completion works for Javascript, Bash, and/or XML files?

**Comment by hoseyjoe** [comment]
xml: Outline, autocomplete works  
js: Outline, autocomplete work  
hx: Outline works  

![idk](https://user-images.githubusercontent.com/2074385/145509095-29f8bc83-13dd-4391-978b-1c3235061a5d.gif)


Another error that came through, maybe related???

org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Internal error.
```
java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Internal error.
	at java.base/java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.get(Unknown Source)
	at org.eclipse.lsp4e.LanguageServerWrapper.lambda$13(LanguageServerWrapper.java:425)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Internal error.
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:209)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
	at org.eclipse.lsp4e.LanguageServerWrapper.lambda$4(LanguageServerWrapper.java:260)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

Tried it on the work computer, both windows 10, both have auto complete issue

**Comment by hoseyjoe** [comment]
1. I installed haxe and left it at default location (C:\HaxeToolkit\haxe).  I changed haxelib to default location (C:\HaxeToolkit\haxe\lib) and code completion works!!
2. I changed haxelib location back to previous location (C:\SDKs\Haxe\haxe\lib) and code completion works!
3. I change haxe to original custom location (C:\SDKs\Haxe\haxe) by running haxesetup.exe  and error now occurs

I restarted HS between each test.

I then noticed that the new install doesnt have haxesetup.exe so I removed my custom install, except lib fodler, and reinstalled from scratch to custom location.  Problem is gone???  Code completion work with -lib.  It appears to have been related to upgrading haxe installations over time??

Anyways I think this can be closed?

**Comment by sebthom** [comment]
Maybe there was a mismatch between your Haxe related environment variables and the actual location where you installed Haxe.

**Comment by hoseyjoe** [comment]
ya, no idea. It doesn't show that error anymore. It was fixed with fresh install of haxe

I have same issue at office.  I can zip the install if you are interested

**Comment by sebthom** [comment]
When you changed the haxelib location, did you set an environment variable for it? Or did you use symlinks?

**Comment by hoseyjoe** [comment]
haxelib setup
then put in path

**Comment by hoseyjoe** [comment]
I just took the installation from the office and replaced the working version with it and I get the error.

Bam!!!  There was a copy of neko.exe in the folder.  Removing that fixed the issue.  In older versions of haxe neko.exe lived beside haxe.exe, I assume.  Issue discovered and solved

**Comment by hoseyjoe** [comment]
Sorry for the noise

**Comment by sebthom** [comment]
I'm glad it works now :)

**Comment by ianharrigan** [comment]
So hang on, what was the resolution? To remove neko.exe?

**Comment by hoseyjoe** [comment]
yes. neko.exe in folder with haxe.exe breaks it. So remove it

**Comment by hoseyjoe** [comment]
Neko in haxe for default install path
C:\HaxeToolkit\neko\neko.exe
haxe is
C:\HaxeToolkit\haxe\haxe.exe

Mine was equivalent
C:\HaxeToolkit\haxe\haxe.exe
C:\HaxeToolkit\haxe\neko.exe (remove this)

**Comment by ianharrigan** [comment]
Thats interesting, i was just about to say i have neko.exe next haxe.exe, but actually, i dont - i separated them a while ago
